### ISSUE TITLE
Ironclad bow does not have infinite arrows

### ISSUE THREAD

**Issue by wuwangwo1234** [Bandit-bytes/too_many_bows#1]
The Ironclad Bow function description says it has Infinite arrows, but in practice it does not have Infinite arrows

forge 1.20.1
too_many_bows-forge-2.1.2

**Comment by Bandit-bytes** [comment]
Ironclaud should not have infinite arrows. Only the burnt Relic, can you provide screenshot?

**Comment by wuwangwo1234** [comment]
![Uploading 微信图片_20241203110756.png…]()

**Comment by wuwangwo1234** [comment]
![微信图片_20241203110756](https://github.com/user-attachments/assets/6c171d77-8982-4d3a-9202-df56f7cf5a90)

**Comment by wuwangwo1234** [comment]
The description says there are infinite arrows, but you can't shoot without arrows

**Comment by Bandit-bytes** [comment]
Interesting, that's definitely an addition I was planning but thought I removed that from the tooltip. Thank you for providing that. I will fix that!

**Comment by Bandit-bytes** [comment]
updated tooltip in latest version
