### ISSUE TITLE
Regarding missing loot for some bows

### ISSUE THREAD

**Issue by wuwangwo1234** [Bandit-bytes/too_many_bows#2]
I like this mod very much, but when I play the game, I cannot find bows of rare rarity in various loot chests, but other common, uncommon and epic bows with loot from this mod can be seen. I used JER to check, and the loot in the chests\rare_bows file does not have dungeon resource information about these weapons, just like I cannot find weapons that cannot be synthesized, such as vitality weaver and arc of heavens. Do they exist in a treasure chest somewhere in the world?

forge 1.20.1
too_many_bows-forge-2.1.2

**Comment by Bandit-bytes** [comment]
So for the rare and epic bows they are in loot: stronghold/nether bridge.
End city/bastion tower and sometimes jungle tower/pillager outpost

**Comment by Bandit-bytes** [comment]
Can you check these loot areas and let me know if those loot boxes are working.

**Comment by Bandit-bytes** [comment]
i have updated the loot tables for the mod to be included in more loot, but be aware that rare and epic bows will mostly only be found in nether or the end

**Comment by wuwangwo1234** [comment]
I downloaded the latest version and used the command to get the items in the loot table, but the loot table in rare is the only one that cannot be obtained. I also searched for treasure chests in the nether and end cities in the new chunks. The treasure chests in the end cities have epic items, and the nether fortresses have nothing. It seems that the bows in the loot table in rare_bows are the only ones that cannot be found.

**Comment by wuwangwo1234** [comment]
![微信图片_20241204152254](https://github.com/user-attachments/assets/f352aad1-4411-49de-bcd4-2565cfd07f15)

**Comment by Bandit-bytes** [comment]
Oh weird! Okay I will fix this today thank you!

**Comment by Bandit-bytes** [comment]
found the issue i misspelled my own bow name :C
fixed now
