### ISSUE TITLE
Necro Skulls

### ISSUE THREAD

**Issue by SirSwarm** [Bandit-bytes/too_many_bows#3]
I can not, for the life of me, figure out how to get the necro skull needed for the necro flame bow. I have tried just about everything. I have looked in chests everywhere, in all 3 dimensions, and I have even tried throwing wither skulls, and skeleton skulls in both regular, and blue fire. I do not know how to do it. I googled many times to see if anyone else has had this problem, but could not find anything. Please help.

**Comment by Bandit-bytes** [comment]
Necro skull is only found in loot, end city loot. I can make a craft for it in future update

**Comment by Bandit-bytes** [comment]
Removed from mod in latest
